import type { Metadata } from 'next'
import React from 'react'
import Header from './components/Header'

export const metadata: Metadata = {
  title: 'Cool Things',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      {children}
    </>
  )
}
