import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.scss";
import ExternalScripts from "@/config/ExternalScripts";
import React from "react";

const inter = Inter({
    variable: "--font-inter",
    subsets: ['latin']
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <ExternalScripts/>
        <body
            className={`${inter.variable} antialiased`}
        >

        <div className=' container'>
            {children}
        </div>

        </body>
        </html>
    );
}
