import type {Metadata} from "next";
import Script from 'next/script'
import {Inter} from "next/font/google";
import "./globals.scss";

const inter = Inter({
    variable: "--font-inter",
    subsets: ['latin']
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Script strategy={'afterInteractive'} src='https://static.cloudflareinsights.com/beacon.min.js'
                data-cf-beacon='{"token": "11d17913667f4364a2890c9bbb6b3665"}' defer/>
        <Script id="gtm-script" strategy="afterInteractive">
            {`
          (function(w,d,s,l,i){
            w[l]=w[l]||[];
            w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
            var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),
                dl=l!='dataLayer'?'&l='+l:'';
            j.async=true;
            j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
            f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-MWWFJBPW');
        `}
        </Script>
        <body
            className={`${inter.variable}zz antialiased`}
        >
        <noscript>
            <iframe
                src="https://www.googletagmanager.com/ns.html?id=GTM-MWWFJBPW"
                height="0"
                width="0"
                style={{display: 'none', visibility: 'hidden'}}
            ></iframe>
        </noscript>

        <div className=' container'>
            {children}
        </div>

        </body>
        </html>
    );
}
