import type {Metadata} from "next";
import Header from "@/app/(thing)/thing/components";


export const metadata: Metadata = {
    title: "Cool Things",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header/>
            {children}
        </>
    );
}
